// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} url
 * @returns {$CancellablePromise<$models.AnalysisResult | null>}
 */
export function AnalyzeLCSC(url) {
    return $Call.ByID(1393733257, url).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearHistory() {
    return $Call.ByID(3526480461);
}

/**
 * @param {$models.AnalysisResult | null} data
 * @returns {$CancellablePromise<$models.SaveResult | null>}
 */
export function SaveToDatabase(data) {
    return $Call.ByID(3231039631, data).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.AnalysisResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.SaveResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
