// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.Config>}
 */
export function GetConfig() {
    return $Call.ByID(2320765359).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.TableStat[]>}
 */
export function GetDBStats() {
    return $Call.ByID(2734052230).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function PingDB() {
    return $Call.ByID(4174523681);
}

/**
 * @param {$models.Config} cfg
 * @returns {$CancellablePromise<void>}
 */
export function UpdateConfig(cfg) {
    return $Call.ByID(2661587996, cfg);
}

// Private type creation functions
const $$createType0 = $models.Config.createFrom;
const $$createType1 = $models.TableStat.createFrom;
const $$createType2 = $Create.Array($$createType1);
