// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AnalysisResult {
    /**
     * Creates a new AnalysisResult instance.
     * @param {Partial<AnalysisResult>} [$$source = {}] - The source object to create the AnalysisResult.
     */
    constructor($$source = {}) {
        if (!("lcsc_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lcsc_id"] = "";
        }
        if (!("table_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["table_name"] = "";
        }
        if (!("fields" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["fields"] = {};
        }
        if (!("table_names" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["table_names"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["raw_data"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnalysisResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AnalysisResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField2_0($$parsedSource["fields"]);
        }
        if ("table_names" in $$parsedSource) {
            $$parsedSource["table_names"] = $$createField3_0($$parsedSource["table_names"]);
        }
        return new AnalysisResult(/** @type {Partial<AnalysisResult>} */($$parsedSource));
    }
}

export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("ApiKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ApiKey"] = "";
        }
        if (!("BaseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["BaseUrl"] = "";
        }
        if (!("AiModel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["AiModel"] = "";
        }
        if (!("DbFile" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["DbFile"] = "";
        }
        if (!("SystemTag" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SystemTag"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

export class SaveResult {
    /**
     * Creates a new SaveResult instance.
     * @param {Partial<SaveResult>} [$$source = {}] - The source object to create the SaveResult.
     */
    constructor($$source = {}) {
        if (!("part_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["part_id"] = 0;
        }
        if (!("system_tag" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["system_tag"] = "";
        }
        if (!("table_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["table_name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SaveResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveResult(/** @type {Partial<SaveResult>} */($$parsedSource));
    }
}

export class TableStat {
    /**
     * Creates a new TableStat instance.
     * @param {Partial<TableStat>} [$$source = {}] - The source object to create the TableStat.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("records" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["records"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableStat instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TableStat}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TableStat(/** @type {Partial<TableStat>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
